backend: 
  name: github
  repo: matthewjlewis93/wine30
media_folder: images
public_folder: /public
collections:
  - name: "storehours"
    label: "Hours"
    folder: "_includes/_partials/hours"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Open Time", name: "openTime", widget: "string" }
      - { label: "Close Time", name: "closeTime", widget: "string" }